### ISSUE TITLE
EditorBrowsableAttributeFinder failure just started happening

### ISSUE THREAD

**Issue by bording** [Fody/Obsolete#21]
I've started seeing a weird failure on https://github.com/Particular/NServiceBus.AmazonSQS, on both the develop branch and https://github.com/Particular/NServiceBus.AmazonSQS/pull/197

```
[Fody.WeavingTask] Fody: Could not enable HideObsoleteMembers due to problem finding EditorBrowsableAttribute. Disable HideObsoleteMembers and raise an issue detailing what runtime you are compiling against. Inner Exception:System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at ModuleWeaver.FindFromTypes(Collection`1 typeDefinitions) in C:\projects\obsolete\Fody\EditorBrowsableAttributeFinder.cs:line 39
   at ModuleWeaver.FindSystemTypes() in C:\projects\obsolete\Fody\EditorBrowsableAttributeFinder.cs:line 27
```

It's happening for a `netstandard2.0` build being run via msbuild.exe, but only on the build server. Building locally works fine. The `net452` target in the same build also works fine.

We're running Fody 2.4.4 and Obsolete.Fody 4.3.7, but this just started happening even though we've been running with those versions.

 I suspect there is something environmental going on. Given that Fody scans a lot of directories outside of the project, could it be picking up something from another build? Any ideas as to what I could go looking for that might be causing the failure?

[log.txt](https://github.com/Fody/Obsolete/files/1776795/log.txt)

**Comment by SimonCropp** [comment]
can u do a purge of the nuget cache prior to doing a build? i have a suspicion as to the problem and if the purge works i know how to fix it

**Comment by bording** [comment]
I was about to do the purge, but it appears that things are passing now for some reason. Looking at a build log from a passing build, I think I see what's happening.

From the failing build:
```
[22:37:39][Fody.WeavingTask]   Fody:     Fody weaver file added 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.1.0\Obsolete.Fody.dll'
[22:37:39][Fody.WeavingTask]   Fody:     Fody weaver file added 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.2.2\Obsolete.Fody.dll'
[22:37:39][Fody.WeavingTask]   Fody:     Fody weaver file added 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.3.7\netclassicweaver\Obsolete.Fody.dll'
...
[22:37:39][Fody.WeavingTask]   Fody: Found debug symbols at 'C:\BuildAgent\work\f572a372d5976361\src\NServiceBus.AmazonSQS\obj\Release\netstandard2.0\NServiceBus.AmazonSQS.pdb'.
[22:37:39][Fody.WeavingTask]   Fody: Weaver 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.2.2\Obsolete.Fody.dll'.
[22:37:39][Fody.WeavingTask]   Fody:   Initializing weaver
[22:37:39][Fody.WeavingTask]   Fody:   Loading 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.2.2\Obsolete.Fody.dll' from cache.
[22:37:39][Fody.WeavingTask]     Fody/Obsolete:   Executing Weaver 
```

From the passing build:
```
[17:43:36][Fody.WeavingTask]   Fody:     Fody weaver file added 'C:\Users\buildagent\.nuget\packages\obsolete.fody\3.1.0\Obsolete.Fody.dll'
[17:43:36][Fody.WeavingTask]   Fody:     Fody weaver file added 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.0.3\Obsolete.Fody.dll'
[17:43:36][Fody.WeavingTask]   Fody:     Fody weaver file added 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.0.4\Obsolete.Fody.dll'
[17:43:36][Fody.WeavingTask]   Fody:     Fody weaver file added 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.1.0\Obsolete.Fody.dll'
[17:43:36][Fody.WeavingTask]   Fody:     Fody weaver file added 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.2.2\Obsolete.Fody.dll'
[17:43:36][Fody.WeavingTask]   Fody:     Fody weaver file added 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.3.2\Obsolete.Fody.dll'
[17:43:36][Fody.WeavingTask]   Fody:     Fody weaver file added 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.3.7\netclassicweaver\Obsolete.Fody.dll'
...
[17:43:36][Fody.WeavingTask]   Fody: Found debug symbols at 'C:\BuildAgent\work\f572a372d5976361\src\NServiceBus.AmazonSQS\obj\Release\netstandard2.0\NServiceBus.AmazonSQS.pdb'.
[17:43:37][Fody.WeavingTask]   Fody: Weaver 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.3.2\Obsolete.Fody.dll'.
[17:43:37][Fody.WeavingTask]   Fody:   Initializing weaver
[17:43:37][Fody.WeavingTask]   Fody:   Loading 'C:\Users\buildagent\.nuget\packages\obsolete.fody\4.3.2\Obsolete.Fody.dll' from cache.
[17:43:37][Fody.WeavingTask]     Fody/Obsolete:   Executing Weaver 
[17:43:37][Fody.WeavingTask]     Fody/Obsolete:   	Removing reference to 'Obsolete.dll'.
[17:43:37][Fody.WeavingTask]     Fody/Obsolete:   Finished 'Obsolete' in 5ms 
```

In both cases, it's picking the wrong version of the weaver assembly. I've got 4.3.7 installed.

**Comment by SimonCropp** [comment]
can u try fody 2.4.5

**Comment by bording** [comment]
@SimonCropp That does seem to allow it to find the correct version of the weaver assembly because it's now finding the file in the PackageDefinitions section instead of falling back to scanning the "the MsBuildThisFileDirectory parent" folder.

However, what if it did need to fall back to that folder for some reason? Why was the correct version not being chosen from that folder? It doesn't seem reasonable to expect that the NuGet cache folder is only going to have a single version of the weaver assembly in it.

**Comment by SimonCropp** [comment]
The parent folder logic is legacy from when packages existed in the solution dir. moving forward the correct package versions are passed via msbuild, ie when using the new sdk project msbuild style. The fact that you regressed to the legacy seems to be due to an incorrect assumption on my part as to the logic of then to ise the new sdk approch. I assmed a prop would always exist. But the fact that it broke now is strange, i smoke tested it when released, but it consistently failes for me now. So perhaps it was a breaking change in an undocumented behaviour of msbuild 

I will wire up some periodic builds to prevent a regression

**Comment by bording** [comment]
> The parent folder logic is legacy from when packages existed in the solution dir. moving forward the correct package versions are passed via msbuild,

Cool. That works for me! Sounds like this is fixed then.
